---
title: "BIOL606_hw_Lecture06_Fahey"
author: "Sean Fahey"
date: "2023-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggfortify)
```

## In-Class stuff
```{r}
soay = read.csv("SoaySheepFitness.csv")

soaymodel = lm(
  fitness ~ body.size,
  data = soay
)
autoplot(soaymodel) # first we plot the residuals, etc.
anova(soaymodel) # then we do an anova to check how good our model is
print("--------------------------------------------------------")
summary(soaymodel) # then we print the summary to check coefficients (slope and intercept) and significance for each variable
```

```{r}
# glm can be better for count data (like population numbers, etc.)
soayglm = glm(
  fitness ~ body.size,
  data = soay,
  family = 'poisson' #alternatively I can use a quasipoisson, then change anova test method from Chi to F. This is used when residual deviance is way higher than the number of degrees of freedom. Not relevant for this data.
)
autoplot(soayglm)
anova(soayglm, test="Chi") # specify the test for glm
print("--------------------------------------------------------")
summary(soayglm)
```
```{r}
ggplot(
  soay,
  aes(
    x = body.size,
    y = fitness
  )) + 
  
  geom_point(
    size=2,
    shape=20
  ) +
  
  geom_smooth(
    formula = "y~x",
    method='lm',
    size = 1,
    linetype = 2,
    se = FALSE
  ) +
  
  theme_minimal() +
  labs(
    x = "Body Size",
    y = "Fitness"
  )
```


## Homework
```{r importing data}

ccdmg <- read.csv("lecture5_cucumberdamage.csv")
# factorize strings (categoricals)
ccdmg$pollination <- as.factor(ccdmg$pollination)
ccdmg$herbivory <- as.factor(ccdmg$herbivory)

summary(ccdmg)
head(ccdmg)
glimpse(cfdata)

```


```{r question 1}
# Answer the question:  Is the total number of fruits produced affected by herbivore damage to leaves (i.e., "leafdamage") and hand-pollination treatments? (Start with a general linear model and proceed from there)

leafmodel = lm(
  totalfruits ~ leafdamage * pollination,
  data = ccdmg
)

autoplot(leafmodel)
anova(leafmodel)
summary(leafmodel)

# Residuals for the fitted values are heteroscedastic and don't look super great.
# leaf damage has a statistically significant (Df: 196, F: 31.7631, p-value: 6e-8) slightly negative effect on the number of fruits (slope: -0.18345). Pollination method doesn't seem to matter.
```


```{r question 2}
# Make a figure of the results, with separate lines for the two pollination treatments. 

ccplot = ggplot(
  ccdmg,
  aes(
    x = leafdamage,
    y = totalfruits,
    color = pollination
  )
) + 
  
  geom_point(
    shape = 1,
    size = 1
  ) + 
  
  theme_minimal() +
  geom_smooth(
    formula = y~x, # this is the default, but adding it suppresses a warning
    method = 'lm',
    se=FALSE, # get rid of the shaded confidence intervals
    linewidth = 0.5,
    linetype = 2
  ) +
  
  labs(
    x = "Herbavore Leaf Damage",
    y = "Total Number of Fruits",
    title = "Number of Fruits v. Herbavore Damage",
    subtitle = "For 2 Pollination Methods",
  )

ccplot

# Herbivore leaf damage has a negative effect on total number of fruits, regardless of pollination.
```


```{r question 3}
# Repeat steps 1 and 2, but instead of "leafdamage," use the categorical treatment variable "herbivory". Think about what the figure will look like for this scenario.

# Herbavory is a categorical, so the summary figure will need to be a boxplot. Also the residuals plot will have specific values for x.


herbmodel = lm(
  totalfruits ~ herbivory * pollination,
  data = ccdmg
)

autoplot(herbmodel)
anova(herbmodel)
summary(herbmodel)
```


```{r question 3 cont.}

herbplot = ggplot(
  ccdmg,
  aes(
    x = herbivory,
    y = totalfruits,
    color = pollination
  )
) + 
  
  geom_boxplot(
    outlier.colour = "Black",
    outlier.shape = 4,
    show.legend = TRUE,
    fill = "lightgrey"
  ) + 
  
  theme_minimal() +
  labs(
    x = "Herbivory",
    y = "Total Number of Fruits",
    title = "Number of Fruits for each Herbivory",
    subtitle = "For 2 Pollination Methods",
  )

herbplot

# looks like herbivory "H" is different than the others. 
```





















